/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projekbelahketupat;

/**
 *
 * @author ACER
 */
public class FrameTampil extends javax.swing.JFrame {

    /**
     * Creates new form FrameTampil
     */
    public FrameTampil() {
        initComponents();
        
        BangunGeometri.logTarget = jTextArea1;
        
        // Bikin tampilan text area jadi hitam hijau (opsional)
        jTextArea1.setBackground(new java.awt.Color(15, 15, 15));
        jTextArea1.setForeground(new java.awt.Color(0, 255, 0));
        jTextArea1.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        MenuBar = new javax.swing.JMenuBar();
        Manual = new javax.swing.JMenu();
        mCheckBoxBK = new javax.swing.JCheckBoxMenuItem();
        mCheckBoxLimas = new javax.swing.JCheckBoxMenuItem();
        mCheckBoxPrisma = new javax.swing.JCheckBoxMenuItem();
        jMenuInput = new javax.swing.JMenuItem();
        Random = new javax.swing.JMenu();
        rCheckBoxBK = new javax.swing.JCheckBoxMenuItem();
        rCheckBoxLimas = new javax.swing.JCheckBoxMenuItem();
        rCheckBoxPrisma = new javax.swing.JCheckBoxMenuItem();
        cbMultithreading = new javax.swing.JCheckBoxMenuItem();
        RandomRun = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("BELAH KETUPAT");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        Manual.setText("Input Manual");
        Manual.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                ManualMenuSelected(evt);
            }
        });

        mCheckBoxBK.setSelected(true);
        mCheckBoxBK.setText("Belah Ketupat");
        Manual.add(mCheckBoxBK);

        mCheckBoxLimas.setSelected(true);
        mCheckBoxLimas.setText("Limas Belah Ketupat");
        mCheckBoxLimas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCheckBoxLimasActionPerformed(evt);
            }
        });
        Manual.add(mCheckBoxLimas);

        mCheckBoxPrisma.setSelected(true);
        mCheckBoxPrisma.setText("Prisma Belah Ketupat");
        Manual.add(mCheckBoxPrisma);

        jMenuInput.setText("Input Data");
        jMenuInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuInputActionPerformed(evt);
            }
        });
        Manual.add(jMenuInput);

        MenuBar.add(Manual);

        Random.setText("Random");

        rCheckBoxBK.setSelected(true);
        rCheckBoxBK.setText("Belah Ketupat");
        rCheckBoxBK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rCheckBoxBKActionPerformed(evt);
            }
        });
        Random.add(rCheckBoxBK);

        rCheckBoxLimas.setSelected(true);
        rCheckBoxLimas.setText("Limas Belah Ketupat");
        Random.add(rCheckBoxLimas);

        rCheckBoxPrisma.setSelected(true);
        rCheckBoxPrisma.setText("Prisma Belah Ketupat");
        rCheckBoxPrisma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rCheckBoxPrismaActionPerformed(evt);
            }
        });
        Random.add(rCheckBoxPrisma);

        cbMultithreading.setSelected(true);
        cbMultithreading.setText("Multithreading");
        cbMultithreading.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMultithreadingActionPerformed(evt);
            }
        });
        Random.add(cbMultithreading);

        RandomRun.setText("Run");
        RandomRun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RandomRunMouseClicked(evt);
            }
        });
        RandomRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RandomRunActionPerformed(evt);
            }
        });
        Random.add(RandomRun);

        MenuBar.add(Random);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel1)
                .addContainerGap(122, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ManualMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_ManualMenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_ManualMenuSelected

    private void rCheckBoxPrismaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rCheckBoxPrismaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rCheckBoxPrismaActionPerformed

    private void rCheckBoxBKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rCheckBoxBKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rCheckBoxBKActionPerformed

    private void mCheckBoxLimasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCheckBoxLimasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mCheckBoxLimasActionPerformed

    private void RandomRunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RandomRunMouseClicked
        // TODO add your handling code here:
        

        
    }//GEN-LAST:event_RandomRunMouseClicked

    private void jMenuInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuInputActionPerformed
        // TODO add your handling code here:                 
        
        // 1. Cek apakah ada yang dicentang
        if (!mCheckBoxBK.isSelected() && !mCheckBoxPrisma.isSelected() && !mCheckBoxLimas.isSelected()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Centang minimal satu bangun di menu Input Manual!");
            return;
        }

        // 2. Siapkan kolom input
        javax.swing.JTextField d1Field = new javax.swing.JTextField();
        javax.swing.JTextField d2Field = new javax.swing.JTextField();
        javax.swing.JTextField tField = new javax.swing.JTextField();

        // 3. LOGIKA JENIUS: Cek apakah kita butuh input Tinggi?
        boolean butuhTinggi = mCheckBoxPrisma.isSelected() || mCheckBoxLimas.isSelected();

        // 4. Susun form secara dinamis menggunakan ArrayList
        java.util.ArrayList<Object> formItems = new java.util.ArrayList<>();
        formItems.add("Input Diagonal 1:");
        formItems.add(d1Field);
        formItems.add("Input Diagonal 2:");
        formItems.add(d2Field);
        
        // Tinggi HANYA dimunculkan kalau butuhTinggi = true
        if (butuhTinggi) {
            formItems.add("Input Tinggi (Untuk Prisma/Limas):");
            formItems.add(tField);
        }

        // 5. Tampilkan Pop-up
        int option = javax.swing.JOptionPane.showConfirmDialog(this, formItems.toArray(), "Input Manual Dinamis", javax.swing.JOptionPane.OK_CANCEL_OPTION);

        if (option == javax.swing.JOptionPane.OK_OPTION) {
            try {
                // Tarik data
                double d1 = Double.parseDouble(d1Field.getText());
                double d2 = Double.parseDouble(d2Field.getText());
                double t = 0;
                
                if (butuhTinggi) {
                    t = Double.parseDouble(tField.getText());
                }

                jTextArea1.append("\n>> [MANUAL] Memproses (D1=" + d1 + ", D2=" + d2 + (butuhTinggi ? ", T=" + t : "") + ") secara Synchronous...\n");

                
                if (mCheckBoxBK.isSelected()) {
                    jTextArea1.append("-> Menghitung Belah Ketupat...\n");
                    BelahKetupat bk = new BelahKetupat();
                    
                    bk.setD1(d1);
                    bk.setD2(d2);
                    
                    bk.tampilkanHasil(); // Panggil langsung method-nya
                }
                
                if (mCheckBoxPrisma.isSelected()) {
                    jTextArea1.append("-> Menghitung Prisma Belah Ketupat...\n");
                    PrismaBelahKetupat prisma = new PrismaBelahKetupat(d1, d2, t);
                    
                    prisma.setD1(d1);
                    prisma.setD2(d2);
                    prisma.setTinggiPrisma(t);
                    
                    prisma.tampilkanHasil(); // Panggil langsung method-nya
                }
                
                if (mCheckBoxLimas.isSelected()) {
                    jTextArea1.append("-> Menghitung Limas Belah Ketupat...\n");
                    
                    LimasBelahKetupat limas = new LimasBelahKetupat();
                    
                    
                    limas.setD1(d1);
                    limas.setD2(d2);
                    limas.setTinggiLimas(t);
                    
                    limas.tampilkanHasil(); // Panggil langsung method-nya
                }
                
                // Efek autoscroll ke bawah
                jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());

            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal! Pastikan semua kolom terisi angka.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    
    }//GEN-LAST:event_jMenuInputActionPerformed

    private void RandomRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RandomRunActionPerformed
        // TODO add your handling code here:
     if (!rCheckBoxBK.isSelected() && !rCheckBoxPrisma.isSelected() && !rCheckBoxLimas.isSelected()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Centang minimal satu bangun di menu Random!");
            return;
        }

        // 2. Ambil Status Mode
        boolean pakaiThread = cbMultithreading.isSelected();
        java.util.ArrayList<String> pilihanAktif = new java.util.ArrayList<>();
        if (rCheckBoxBK.isSelected()) pilihanAktif.add("BK");
        if (rCheckBoxPrisma.isSelected()) pilihanAktif.add("PRISMA");
        if (rCheckBoxLimas.isSelected()) pilihanAktif.add("LIMAS");
        
        jTextArea1.append("\n>> RANDOM MODE | MULTITHREADING : " + (pakaiThread ? "ON" : "OFF") + "\n");

        int jumlahData = 100;

        // ========================================================
        // 3. MASTER THREAD (BUNGKUS SEMUANYA DI SINI BIAR GAK FREEZE)
        // ========================================================
        Thread masterThread = new Thread(new Runnable() {
            @Override
            public void run() {

                if (pakaiThread) {
                    // ------------------------------------
                    // JIKA ON: EKSEKUSI PARALEL (BALAPAN)
                    // ------------------------------------
                    Thread[] kumpulanThread = new Thread[jumlahData];

                    for (int i = 0; i < jumlahData; i++) {
                        double randD1 = 10 + (Math.random() * 40);
                        double randD2 = 10 + (Math.random() * 40);
                        double randTinggi = 10 + (Math.random() * 40);

                        BangunGeometri bangun;
                        String jenis = pilihanAktif.get(i % pilihanAktif.size());

                        if (jenis.equals("PRISMA")) {
                            bangun = new PrismaBelahKetupat(randD1, randD2, randTinggi);
                        } else if (jenis.equals("LIMAS")) {
                            bangun = new LimasBelahKetupat(randD1, randD2, randTinggi);
                        } else {
                            bangun = new BelahKetupat(randD1, randD2);
                        }

                        String namaThread = bangun.getClass().getSimpleName() + " - " + i;
                        kumpulanThread[i] = new Thread(bangun, namaThread);
                        kumpulanThread[i].start();
                    }

                    // Sinkronisasi (Tunggu semua beres)
                    for (int i = 0; i < jumlahData; i++) {
                        try { kumpulanThread[i].join(); } catch (InterruptedException e) {}
                    }

                    // Lapor ke GUI kalau sudah selesai
                    javax.swing.SwingUtilities.invokeLater(new Runnable() {
                        @Override
                        public void run() {
                            jTextArea1.append("\n=== MULTITHREADING SELESAI ===\n");
                            jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
                        }
                    });

                } else {
                    // ------------------------------------
                    // JIKA OFF: EKSEKUSI SEKUENSIAL (ANTRE)
                    // ------------------------------------
                    for (int i = 0; i < jumlahData; i++) {
                        double randD1 = 10 + (Math.random() * 40);
                        double randD2 = 10 + (Math.random() * 40);
                        double randTinggi = 10 + (Math.random() * 40);

                        BangunGeometri bangun;
                        String jenis = pilihanAktif.get(i % pilihanAktif.size());

                        if (jenis.equals("PRISMA")) {
                            bangun = new PrismaBelahKetupat(randD1, randD2, randTinggi);
                        } else if (jenis.equals("LIMAS")) {
                            bangun = new LimasBelahKetupat(randD1, randD2, randTinggi);
                        } else {
                            bangun = new BelahKetupat(randD1, randD2);
                        }

                        // Ganti nama Master Thread sementara sesuai objek yang lagi diproses
                        Thread.currentThread().setName(bangun.getClass().getSimpleName() + " - " + i);
                        
                        // Eksekusi langsung (nunggu selesai baru lanjut loop berikutnya)
                        bangun.run();
                    }

                    // Lapor ke GUI kalau sudah selesai
                    javax.swing.SwingUtilities.invokeLater(new Runnable() {
                        @Override
                        public void run() {
                            jTextArea1.append("\n=== SINGLE THREAD SELESAI ===\n");
                            jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
                        }
                    });
                }
            } // Tutup public void run() milik Master Thread
        }); // Tutup Master Thread

        // 4. JALANKAN MASTER THREAD-NYA!
        masterThread.start();
    }//GEN-LAST:event_RandomRunActionPerformed

    private void cbMultithreadingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMultithreadingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMultithreadingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameTampil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameTampil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameTampil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTampil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameTampil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Manual;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu Random;
    private javax.swing.JMenuItem RandomRun;
    private javax.swing.JCheckBoxMenuItem cbMultithreading;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuInput;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JCheckBoxMenuItem mCheckBoxBK;
    private javax.swing.JCheckBoxMenuItem mCheckBoxLimas;
    private javax.swing.JCheckBoxMenuItem mCheckBoxPrisma;
    private javax.swing.JCheckBoxMenuItem rCheckBoxBK;
    private javax.swing.JCheckBoxMenuItem rCheckBoxLimas;
    private javax.swing.JCheckBoxMenuItem rCheckBoxPrisma;
    // End of variables declaration//GEN-END:variables
}
